global:
  domain: argocd.derbserv.hq

server:
  ingress:
    enabled: true

configs:
  params:
    server.insecure: true

  cm:
    # admin.enabled: false

    oidc.config: |
      name: IAM
      issuer: http://iam.stg.derbserv.hq/realms/derbserv
      clientID: $argocd-client-creds:key
      clientSecret: $argocd-client-creds:secret
      requestedScopes: ['openid', 'profile', 'email', 'groups']
 
  rbac:
    policy.default: role:none
    policy.csv: |
      g, argocd-admins, role:admin
      g, argocd-viewers, role:readonly
